name:                adventofcode2019
version:             0.1.0.0
github:              "Dessix/AdventOfCode2019"
license:             MIT
author:              "Dessix"
maintainer:          "Dessix@Dessix.net"
copyright:           "2019 Dessix"

extra-source-files: []

description:         Please see the README on GitHub at <https://github.com/Dessix/AdventOfCode2019#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- lens
- text
- vector

library:
  source-dirs: src

executables:
  adventofcode2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2019

tests:
  adventofcode2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2019
